// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnsVzKhuWLoY5qs_CLQhWx1yM0LTG5rf8',
    appId: '1:557072901026:web:4aa311b7f40f58feed08fb',
    messagingSenderId: '557072901026',
    projectId: 'desafog-ai',
    authDomain: 'desafog-ai.firebaseapp.com',
    storageBucket: 'desafog-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdcPhREw-n3w9h6F5qkfhEJ-3kM9jnSg',
    appId: '1:557072901026:android:f276cf3a11fcbfe0ed08fb',
    messagingSenderId: '557072901026',
    projectId: 'desafog-ai',
    storageBucket: 'desafog-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOcwRqOk5ez8tebML0bQsOiucWMRHvRw',
    appId: '1:557072901026:ios:2ce07194e0459bdded08fb',
    messagingSenderId: '557072901026',
    projectId: 'desafog-ai',
    storageBucket: 'desafog-ai.firebasestorage.app',
    iosBundleId: 'com.desafog.desafogAi',
  );
}
